---
clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - vault
    - golang-external-secrets
    - ansible-automation-platform
    - aap-config
    - openshift-cnv
    - openshift-storage
    - edge-gitops-vms
    - edge-observability-stack

  subscriptions:
    aap-operator:
      name: ansible-automation-platform-operator
      namespace: ansible-automation-platform
      channel: stable-2.5

    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable
      annotations:
        argocd.argoproj.io/sync-wave: "10"

    openshift-data-foundation:
      name: odf-operator
      namespace: openshift-storage
      sequenceJob:
        resourceType: sc
        resourceName: ocs-storagecluster-ceph-rbd
      annotations:
        argocd.argoproj.io/sync-wave: "5"

  projects:
    - hub

  imperative:
    jobs:
      - name: deploy-kubevirt-worker
        playbook: ansible/deploy_kubevirt_worker.yml
        verbosity: -vvv
      - name: clean-golden-images
        playbook: ansible/odf_fix_dataimportcrons.yml
        verbosity: -vvv
    clusterRoleYaml:
      - apiGroups:
          - "*"
        resources:
          - machinesets
          - datavolumes
          - datasources
          - dataimportcrons
        verbs:
          - "*"
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch

  applications:
    aap:
      name: ansible-automation-platform
      namespace: ansible-automation-platform
      project: hub
      chart: ansible-automation-platform-instance
      chartVersion: 0.1.*

    aap-config:
      name: aap-config
      namespace: aap-config
      project: hub
      chart: aap-config
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-aap-config-feo.yaml'

    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*

    openshift-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      project: hub
      chart: openshift-virtualization-instance
      chartVersion: 0.1.*

    odf:
      name: odf
      namespace: openshift-storage
      project: hub
      chart: openshift-data-foundations
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-odf-chart.yaml'

    edge-gitops-vms:
      name: edge-gitops-vms
      namespace: edge-gitops-vms
      project: hub
      chart: edge-gitops-vms
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-egv-feo.yaml'

    edge-observability-stack:
      name: edge-observability-stack
      namespace: edge-observability-stack
      project: hub
      repoURL: https://github.com/validatedpatterns-demos/edge-observability-stack
      chartVersion: main
      path: "."

  # Only the hub cluster here - managed entities are edge nodes
  managedClusterGroups: []
